CREATE DATABASE ADBMS;
USE ADBMS;

CREATE TABLE TBL_AUTHOR
(
	AUTHOR_ID INT PRIMARY KEY,
	AUTHOR_NAME VARCHAR(MAX),
	COUNTRY VARCHAR(MAX)
);

CREATE TABLE TBL_BOOKS
(
	BOOK_ID INT PRIMARY KEY,
	BOOK_TITLE VARCHAR(MAX),
	AUTHOR_ID INT,
	FOREIGN KEY (AUTHOR_ID) REFERENCES TBL_AUTHOR(AUTHOR_ID)
);

INSERT INTO TBL_AUTHOR VALUES(1, 'Anshu', 'India');
INSERT INTO TBL_AUTHOR VALUES(2, 'Devansh', 'Nambia');
INSERT INTO TBL_AUTHOR VALUES(3, 'Chandan', 'South Africa');

INSERT INTO TBL_BOOKS VALUES(1, 'The Deep', 1);
INSERT INTO TBL_BOOKS VALUES(2, 'The Lazy Man', 2);
INSERT INTO TBL_BOOKS VALUES(3, 'Programming With Python', 3);

/*
Types of joins:
1) Inner Join (gives matching records based on common column)
2) LEFT OUTER JOIN (entire left table + comon data)
3) RIGHT OUTER JOIN (entire right table + common data)
4) FULL OUTER JOIN (L + R + C)
5) LEFT EXCLUSIVE JOIN
6) RIGHT EXCLUSIVE JOIN
*/

--SYNTAX:

SELECT B.AUTHOR_NAME, A.BOOK_TITLE AS 'BOOK NAME', B.COUNTRY
FROM TBL_BOOKS AS A
INNER JOIN
TBL_AUTHOR AS B
ON
A.AUTHOR_ID = B.AUTHOR_ID

/*
DCL COMMANDS:
	1) GRANT 
	2) REVOKE

	EMPLOYEE TABLE = CAN PERFORM ANY COMMANDS (PERMISSIONS)

	GRANT PERMISSION/PRIVILEGE ON TBL_NAME TO USER_NAME;
	GRANT SELECT/UPDATE ON EMPLOYEE TO ANSHU;

	REVOKE PERMISSION ON TABLE_NAME FROM USER_NAME;
	REVOKE UPDATE ON EMPLOYEE FROM ANSHU;
*/